language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
services:
  - docker
before_install:
  - docker build --tag ipinput:latest .
  - docker run -d -p 8080:5017 --name ipinput ipinput:latest
install:
  - pip3 install -r requirements.txt
script:
  - python3 test.py